### PR TITLE
Extra backslashes part3

### PR DESCRIPTION
**Pull request by AlphaVS-76**
Can be connected to #121

### CODE REVIEW

**Review by developerasun — COMMENTED** [review]
In Churu.sol file, it throws error 
import err

Changed VS code solidity compiler setting like this 
setGood

and it worked
good

but still doesn't work in CuriousPawoneer.sol like below
notworking

closed other pull requests except this since they are in the same topic :)

**Comment by AlphaVS-76** [comment]
Maybe it's with the solidity version and the compiler version (mostly nightly builds as they are the most gruelling to deal with)

**Review by developerasun — APPROVED** [review]
- approved to remove extra slashes in future contract file

**Comment by developerasun** [comment]
> Maybe it's with the solidity version and the compiler version (mostly nightly builds as they are the most gruelling to deal with)

Adjusted setting.json like below

```json 
{
    "solidity.packageDefaultDependenciesDirectory": "",
    "solidity.packageDefaultDependenciesContractsDirectory": ""
}
```

and create a workspace for blockchain project. And open the workspace in VS code and import error is gone, no need to add relative path for node_modules. 

good

**Pull request merged**
